include: "/src/tscan/webservice/tscanservice/tscan.config.yml"
# if a prefix is used, also update $URLPREFIX in the config.sh
urlprefix: "tscan"
internalurlprefix: "/tscan"
forcehttps: false
base_url: "https://tscan.hum.uu.nl"
use_forwarded_host: false
